import 'package:get/get.dart';

class Message extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    "en_US":{
      "hi": "Hi",
      "language": "Language",
      "khmerLanguage": "Khmer",
      "englishLanguage": "English",
      "chineseLanguage": "Chinese",
      "japaneseLanguage": "Japanese",
      "koreanLanguage": "Korean",
      "theme": "Theme",
      "lightTheme": "Light Theme",
      "darkTheme": "Dark Theme",
      "home": "Home",
      "favorite": "Favorite",
      "cart": "Cart",
      "more": "More",
      "titleLang": "Language",
      "subLang": "English",
      "new": "New"
    },
    "km_KH":{
      "hi": "សួស្តី",
      "language": "ភាសា",
      "khmerLanguage": "ភាសាខ្មែរ",
      "englishLanguage": "ភាសាអង់គ្លេស",
      "chineseLanguage": "ភាសាចិន",
      "japaneseLanguage": "ភាសាជប៉ុន",
      "koreanLanguage": "ភាសាកូរ៉េ",
      "theme": "ផ្ទៃ",
      "lightTheme": "ផ្ទៃភ្លឺ",
      "darkTheme": "ផ្ទៃងងឹត",
      "home": "ដើម",
      "favorite": "ចូលចិត្ត",
      "cart": "កន្រ្តក់",
      "more": "បន្ថែម",
      "titleLang": "ភាសា",
      "subLang": "ភាសាខ្មែរ",
      "new": "ថ្មីៗ"
    },
    "zh_CN": {
      "hi": "你好",
      "language": "语言",
      "khmerLanguage": "高棉语",
      "englishLanguage": "英语",
      "chineseLanguage": "中文",
      "japaneseLanguage": "日语",
      "koreanLanguage": "韩语",
      "theme": "主题",
      "lightTheme": "浅色主题",
      "darkTheme": "深色主题",
      "home": "主页",
      "favorite": "收藏",
      "cart": "购物车",
      "more": "更多",
      "titleLang": "语言",
      "subLang": "中文",
      "new": "新的",
    },
    "ja_JP": {
      "hi": "こんにちは",
      "language": "言語",
      "khmerLanguage": "クメール語",
      "englishLanguage": "英語",
      "chineseLanguage": "中国語",
      "japaneseLanguage": "日本語",
      "koreanLanguage": "韓国語",
      "theme": "テーマ",
      "lightTheme": "ライトテーマ",
      "darkTheme": "ダークテーマ",
      "home": "ホーム",
      "favorite": "お気に入り",
      "cart": "カート",
      "more": "もっと見る",
      "titleLang": "言語",
      "subLang": "日本語",
      "new": "新しい"
    },
    "ko_KR": {
      "hi": "안녕하세요",
      "language": "언어",
      "khmerLanguage": "크메르어",
      "englishLanguage": "영어",
      "chineseLanguage": "중국어",
      "japaneseLanguage": "일본어",
      "koreanLanguage": "한국어",
      "theme": "테마",
      "lightTheme": "라이트 테마",
      "darkTheme": "다크 테마",
      "home": "홈",
      "favorite": "즐겨찾기",
      "cart": "장바구니",
      "more": "더보기",
      "titleLang": "언어",
      "subLang": "한국어",
      "new": "새로운",
    }
  };

}