// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gc7dEpoNizF_KQ2l8FrbvjPwjjb4mC4',
    appId: '1:864985901610:web:dd534432e65585d0c6f153',
    messagingSenderId: '864985901610',
    projectId: 'productfb-443b8',
    authDomain: 'productfb-443b8.firebaseapp.com',
    storageBucket: 'productfb-443b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1n4IMNZLwDZu9JQPKygnBdubwExjLnA',
    appId: '1:864985901610:android:55e6c5ef957e4224c6f153',
    messagingSenderId: '864985901610',
    projectId: 'productfb-443b8',
    storageBucket: 'productfb-443b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUjoSjPmdNKGlkvacknrWNikMUKnz1A8',
    appId: '1:864985901610:ios:59bb13d8ad865a0ec6f153',
    messagingSenderId: '864985901610',
    projectId: 'productfb-443b8',
    storageBucket: 'productfb-443b8.firebasestorage.app',
    iosBundleId: 'com.example.homeworks01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3gc7dEpoNizF_KQ2l8FrbvjPwjjb4mC4',
    appId: '1:864985901610:web:0085e39dc08b1e2cc6f153',
    messagingSenderId: '864985901610',
    projectId: 'productfb-443b8',
    authDomain: 'productfb-443b8.firebaseapp.com',
    storageBucket: 'productfb-443b8.firebasestorage.app',
  );
}
